version: '3'

services:
  mongo:
    image: mongo:4.4.4
    container_name: mongo-dev
    restart: always
    networks:
      - dev-network
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"

  fake-smtp:
    build: github.com/Nilhcem/FakeSMTP
    image: fake-smtp
    volumes:
      - '.tmp:/output'
    ports:
      - "250:25"

networks:
  dev-network:
    driver: bridge
