version: '3'

services:
  mailserver-mongo:
    image: mongo:latest
    container_name: mailserver-mongo
    restart: always
    networks:
      - dev-network
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"
    command: --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=santalucia
      - MONGO_INITDB_ROOT_PASSWORD=Santa-Lucia-Mailserver2022

  fake-smtp:
    image: ghusta/fakesmtp:2.0
    volumes:
      - '.tmp:/var/mail'
    ports:
      - "250:25"

networks:
  dev-network:
    driver: bridge
