version: "3"

services:
  api-server:
    build:
      context: .
    container_name: mailserver
    image: sapza/mailserver:2.0.1
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URL=mongodb://mongo/mailserver
    volumes:
      - ./logs:/logs
      - ./data:/
    networks:
      - app-network
    ports:
      - "3000:3000"
      - "25:25"

  mongo:
    image: mongo:latest
    container_name: mongo-dev
    restart: always
    networks:
      - app-network
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge
